/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
   @Test void roll_dice() {
       Library systemUnderTest = new Library();
       ArrayList<Integer> arr = systemUnderTest.roll(3);
       assertEquals(3, arr.size(), "There are 3 items in the array that was returned.");
       assertNotEquals(4, arr.size());
   }

   @Test void contains_duplicates() {
       Library systemUnderTest = new Library();
       ArrayList<Integer> arr = new ArrayList<>();
       arr.add(1);
       arr.add(2);
       arr.add(1);

       boolean result = systemUnderTest.containDuplicates(arr);
       assertEquals(true, result, "Should return true; There are duplicates");
   }

   @Test void calculate_averages(){
       Library systemUnderTest = new Library();
       int[] average = {1, 2, 3};
       int result = systemUnderTest.calculateAverage((average));
       assertEquals(2, result, "Should equal.");
   }

    @Test void arrays_of_arrays(){
        Library systemUnderTest = new Library();
        int[][] numbers = {
                {1, 2, 3},
                {4, 5, 6},
                {1, 1, 1}
        };
        String result = systemUnderTest.averageArray(numbers);
        int[] correct = {1, 1, 1};
        // Need to properly return an array and find a way to compare
         assertEquals(Arrays.toString(correct), result, "Should equal true; [1, 1, 1]");
    }

    @Test void weather_data() {
        Library systemUnderTest = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String expectedResult = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n";
        String actualResult = systemUnderTest.weatherData(weeklyMonthTemperatures);
        System.out.println(actualResult);
        assertEquals(expectedResult,  actualResult, "Expected result should match Actual result");
    }

    @Test void tallying_election() {

        Library systemUnderTest = new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String expectedResult = "Bush received the most votes!";
        String actualResult = systemUnderTest.tally(votes);
        assertEquals(expectedResult,  actualResult, "Expected result should match Actual result");
    }
}
