/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void create_a_restaurant() {
        Restaurant chilis = new Restaurant("Chilis", 3);
        boolean expectedResult = true;
        boolean actualResult = chilis instanceof Restaurant;
        String expectedStringResult =
                "Chilis\n" +
                "0.0/5\n" +
                "$$$";
        String actualStringResult = chilis.toString();
        System.out.println(chilis.toString());
        assertEquals(expectedResult, actualResult);
        assertEquals(expectedStringResult, actualStringResult);
    }

    @Test void create_a_review() {
        Restaurant chilis = new Restaurant("Chilis", 3);
        Review testReview = new Review("Testing body paragraph", "Jenner Dulce", 5, chilis);
        boolean expectedResult = true;
        boolean actualResult = testReview instanceof Review;
        String expectedStringResult =
                "Chilis\n" +
                "Written by: Jenner Dulce\n" +
                "Body: Testing body paragraph\n" +
                "5.0/5";
        String actualStringResult = testReview.toString();
        assertEquals(expectedResult, actualResult);
    }

    @Test void add_review_to_restauraunt() {
        Restaurant chilis = new Restaurant("Chilis", 3);
        Review testReview = new Review("Testing body paragraph", "Jenner Dulce", 5, chilis);
        chilis.addReview(testReview);
        int expectedResult = 1;
        int actualResult = chilis.totalReviews;
        assertEquals(expectedResult, actualResult);
    }
    @Test void stars_calculator() {
        Restaurant chilis = new Restaurant("Chilis", 3);
        Review testReview = new Review("Testing body paragraph", "Jenner Dulce", 5, chilis);
        Review testReviewTwo = new Review("Testing body paragraph", "Jenner Dulce", 5, chilis);
        chilis.addReview(testReview);
        chilis.addReview(testReviewTwo);
        float expectedResult = 5.0f;
        float actualResult = (float) chilis.stars;
        assertEquals(expectedResult, actualResult);
    }
}
