/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void linter() {
        App systemUnderTest = new App();
        String filePath = "/Users/jenner/codefellows/Java-401/java-fundamentals/linter/app/src/main/resources/gates.js";
        String expectedResult = "Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 15: Missing semicolon.\n" +
                "Line 26: Missing semicolon.\n" +
                "Line 28: Missing semicolon.\n" +
                "Line 32: Missing semicolon.\n" +
                "Line 36: Missing semicolon.\n" +
                "Line 40: Missing semicolon.\n" +
                "Line 41: Missing semicolon.\n" +
                "Line 50: Missing semicolon.\n" +
                "Line 51: Missing semicolon.\n" +
                "Line 59: Missing semicolon.\n" +
                "Line 60: Missing semicolon.\n" +
                "Line 61: Missing semicolon.\n" +
                "Line 62: Missing semicolon.\n" +
                "Line 64: Missing semicolon.\n" +
                "Line 70: Missing semicolon.\n" +
                "Line 71: Missing semicolon.\n" +
                "Line 72: Missing semicolon.\n" +
                "Line 73: Missing semicolon.\n" +
                "Line 74: Missing semicolon.\n" +
                "Line 76: Missing semicolon.\n" +
                "Line 77: Missing semicolon.\n" +
                "Line 78: Missing semicolon.\n" +
                "Line 79: Missing semicolon.\n" +
                "Line 80: Missing semicolon.\n" +
                "Line 82: Missing semicolon.\n" +
                "Line 83: Missing semicolon.\n" +
                "Line 84: Missing semicolon.\n" +
                "Line 85: Missing semicolon.\n" +
                "Line 86: Missing semicolon.\n" +
                "Line 88: Missing semicolon.\n" +
                "Line 89: Missing semicolon.\n" +
                "Line 90: Missing semicolon.\n" +
                "Line 91: Missing semicolon.\n" +
                "Line 92: Missing semicolon.\n" +
                "Line 94: Missing semicolon.\n" +
                "Line 95: Missing semicolon.\n" +
                "Line 96: Missing semicolon.\n" +
                "Line 97: Missing semicolon.\n" +
                "Line 98: Missing semicolon.\n" +
                "Line 99: Missing semicolon.\n" +
                "Line 100: Missing semicolon.\n" +
                "Line 101: Missing semicolon.\n" +
                "\n" +
                "\n" +
                "Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.\n" +
                "\n" +
                "You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.\n" +
                "\n" +
                "See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings\n" +
                "\n" +
                "BUILD SUCCESSFUL in 309ms\n" +
                "3 actionable tasks: 1 executed, 2 up-to-date\n" +
                "9:05:26 PM: Task execution finished ':app:App.main()'.\n";
        String actualResult = systemUnderTest.linter("/Users/jenner/codefellows/Java-401/java-fundamentals/linter/app/src/main/resources/gates.js");
        assertEquals(expectedResult, actualResult, "Expected result should equal Actual result.");
    }
}
